# Generated by Django 4.1.6 on 2023-02-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, upload_to='ImagemProjetos/%Y/%m/%d')),
                ('descricao', models.TextField()),
                ('link_projeto', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
