# Generated by Django 4.1.6 on 2023-02-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_projetos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='legenda',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
