# Generated by Django 4.1.6 on 2023-02-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_projetos_legenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='legenda',
            field=models.CharField(max_length=255),
        ),
    ]
